services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  notissimus.pointertracking.api:
    image: notissimus.pointertracking.api
    ports:
      - 80:8080
    build:
      context: .
      dockerfile: Notissimus.PointerTracking.Api/Dockerfile